### ISSUE TITLE
BigLab1-D分支添加电影后ID无效

### ISSUE THREAD

**Issue by Z-ls** [web-application-bigLab1/web-application1-bigLab#4]
## 截图
![image](https://user-images.githubusercontent.com/5840620/167269005-d593a338-bc3e-4d8c-bf62-cd125a7a5ada.png)
## 复现
添加电影之后编辑已添加电影
## 分析
`<AppRoute>`中存在 
```
<Link to="/add" state={{
    newId: props.newId
    }}>
    <button type="button"
        className="btn btn-lg btn-primary fixed-right-bottom">&#43;
    </button>
</Link>
```
但是在`<Routes>`中
```
<Route path="/" element={<AppRoute filter="All"
          films={filmList}
          deleteFilm={filmFunctions.deleteFilm} />} />
```
并没有传入newId的state
## 建议解决方法
并不建议直接加入newId的state，因为v1.0-beta版本的代码在这部分仍然存在BUG会导致ID重复。
v1.0 branch 上的 v1.1版本代码已经修复了代码重复的bug，但是解决方法效率偏低建议作为最后手段使用。

**Comment by Z-ls** [comment]
附上v1.1版本取得newId的函数。重复遍历数组取得最小闲置ID，O(N^2)。
```
this.findFirstAvailableId = () => {
        let i = 0;
        while(filmList.map(f => f.id).includes(i)) i++;
        return i;
    }
```

**Comment by Fayouou** [comment]
nailed it!
